# Generated by Django 4.2.7 on 2023-12-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.TextField(default='Abdul Khaleq'),
        ),
    ]
